package co.main.inventario.vistas;
import co.main.inventario.dao.ProductoDao;
import co.main.inventario.modelo.Producto;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */

public class ProductoFrm extends javax.swing.JFrame {

   private ProductoDao productoDao;
   private Producto producto;
    
    public ProductoFrm() {
        initComponents();
        this.productoDao = new ProductoDao();
        this.producto = new Producto();
        loadTable();
         btnNuevo.doClick();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spvalor = new javax.swing.JSpinner();
        spcantidad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproductos = new javax.swing.JTable();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JToggleButton();
        btnNuevo = new javax.swing.JButton();
        txtfiltro = new javax.swing.JTextField();
        btnfiltrar = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        cmbParametroFiltro = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 22));

        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 103, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 103, -1));

        txtnombre.setNextFocusableComponent(txtmarca);
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 34, 460, -1));

        txtcodigo.setNextFocusableComponent(txtnombre);
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, 460, -1));

        jLabel4.setText("Valor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 22));

        spvalor.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        spvalor.setNextFocusableComponent(btnguardar);
        jPanel1.add(spvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 460, -1));

        spcantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spcantidad.setNextFocusableComponent(spvalor);
        jPanel1.add(spcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 130, 460, -1));

        jLabel5.setText("Marca:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 103, -1));

        txtmarca.setNextFocusableComponent(txtmodelo);
        jPanel1.add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 68, 460, -1));

        jLabel7.setText("Modelo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 103, -1));

        txtmodelo.setNextFocusableComponent(spcantidad);
        jPanel1.add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 96, 460, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Registro de productos");

        btnguardar.setForeground(new java.awt.Color(0, 153, 0));
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        tblproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproductos);
        if (tblproductos.getColumnModel().getColumnCount() > 0) {
            tblproductos.getColumnModel().getColumn(0).setMinWidth(50);
            tblproductos.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblproductos.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        btnactualizar.setForeground(new java.awt.Color(0, 51, 255));
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setForeground(new java.awt.Color(255, 0, 51));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnNuevo.setForeground(new java.awt.Color(255, 102, 0));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnfiltrar.setText("Filtrar Registros");
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });
        btnfiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnfiltrarKeyPressed(evt);
            }
        });

        btnLoad.setText("Load Table");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        cmbParametroFiltro.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Codigo  producto", "Nombre producto" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbParametroFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnactualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfiltrar)
                    .addComponent(btnLoad)
                    .addComponent(cmbParametroFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        this.producto.setId(null);
        this.producto.setDescripcion(txtnombre.getText());
       this.producto.setCodigo(txtcodigo.getText());
       this.producto.setCantidad(Integer.valueOf(spcantidad.getValue().toString()));
       this.producto.setValor( Double.valueOf(spvalor.getValue().toString()));
       this.producto.setModelo(txtmodelo.getText());
       this.producto.setMarca(txtmarca.getText());
        try {
             Producto productoCreado = productoDao.registrarProducto(producto);
            
             this.loadTable();
             this.limpiarCampos();
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(rootPane,"Error al crear el producto");
        }
    
      
      
      
    }//GEN-LAST:event_btnguardarActionPerformed

    private void tblproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductosMouseClicked
        // TODO add your handling code here:

        int row = tblproductos.getSelectedRow();
        String id = tblproductos.getModel().getValueAt(row, 0).toString();
        String codigo = tblproductos.getModel().getValueAt(row, 1).toString();
        String nombre = tblproductos.getModel().getValueAt(row, 2).toString();

        String marca = tblproductos.getModel().getValueAt(row, 3) == null ? "" : tblproductos.getModel().getValueAt(row, 3).toString();
        String modelo = tblproductos.getModel().getValueAt(row, 4) == null ? "" : tblproductos.getModel().getValueAt(row, 4).toString();

        String cantidad = tblproductos.getModel().getValueAt(row, 5).toString();
        String valor = "";
        //El valor llega con un signo de $ por lo tanto toco limpiarlo
        StringTokenizer tokens = new StringTokenizer(tblproductos.getModel().getValueAt(row, 6).toString(), "$");
        while (tokens.hasMoreElements()) {
            valor = tokens.nextElement().toString();

        }

        this.txtcodigo.setText(codigo);
        this.txtmarca.setText(marca);
        this.txtnombre.setText(nombre);
        this.txtmodelo.setText(modelo);
        this.spcantidad.setValue(Integer.valueOf(cantidad));
        this.spvalor.setValue(Double.valueOf(valor));
        btnguardar.setEnabled(false);
        btnactualizar.setEnabled(true);
        btneliminar.setEnabled(true);


    }//GEN-LAST:event_tblproductosMouseClicked

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
       int row = tblproductos.getSelectedRow();  
       String id =  tblproductos.getModel().getValueAt(row, 0).toString(); 
       this.producto.setId(Long.valueOf(id));
       this.producto.setDescripcion(txtnombre.getText());
       this.producto.setCodigo(txtcodigo.getText());
       
       this.producto.setCantidad(Integer.parseInt(spcantidad.getValue().toString()));
       this.producto.setValor( Double.parseDouble(spvalor.getValue().toString()));
       this.producto.setModelo(txtmodelo.getText());
       this.producto.setMarca(txtmarca.getText());
        try {
             Producto productoCreado = productoDao.registrarProducto(producto);
              
             System.err.println("Producto created: "+productoCreado.toString());
             this.loadTable();
             this.limpiarCampos();
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(rootPane,"Error al crear el producto");
        }
        
        
         btnNuevo.doClick();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int row = tblproductos.getSelectedRow();
        String id =  tblproductos.getModel().getValueAt(row, 0).toString();
       boolean accion =  this.productoDao.eliminar(Long.parseLong(id));
       if(accion){
          JOptionPane.showMessageDialog(rootPane, "Producto eliminado...");
       }else{
         JOptionPane.showMessageDialog(rootPane, "Producto No eliminado...");
       }
       this.loadTable();
       btnNuevo.doClick();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        btnguardar.setEnabled(true);
        btnactualizar.setEnabled(false);
        btneliminar.setEnabled(false);
        this.limpiarCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
        //Determinar el campo por el cual se va a filtrar la consulta
        int index = cmbParametroFiltro.getSelectedIndex();
          String parametro = txtfiltro.getText();
        String col[]= new String[]{"id","codigo","nombre","marca","modelo","cantidad","valor"};
         List<Producto> lista = new ArrayList<>();
        if(index == 0){
           lista = productoDao.buscarByCodigo(parametro);
        
        }else{
            lista = productoDao.buscarByNombre(parametro);
           
        }
        
      
    
     
   
      DefaultTableModel tableModel = new DefaultTableModel(null,col);
      
     
      
      lista.forEach(pr->{
       
        tableModel.addRow(new Object[]{
          pr.getId(),
            pr.getCodigo(),
            pr.getDescripcion(),
            pr.getMarca(),
            pr.getModelo(),
            pr.getCantidad(),
            "$"+pr.getValor()
        
        });
      
      });
      
      
      
      
      
      
      tblproductos.setModel(tableModel);
      
        this.AjusteTabla();
        
        
    }//GEN-LAST:event_btnfiltrarActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
         this.loadTable();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnfiltrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnfiltrarKeyPressed
         if(evt.getKeyCode()==evt.VK_ENTER){
                   btnfiltrar.doClick();
                }
    }//GEN-LAST:event_btnfiltrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void startFrm(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JToggleButton btneliminar;
    private javax.swing.JButton btnfiltrar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cmbParametroFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spcantidad;
    private javax.swing.JSpinner spvalor;
    private javax.swing.JTable tblproductos;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtfiltro;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

  public void loadTable(){
      String col[]= new String[]{"id","codigo","nombre","marca","modelo","cantidad","valor"};
    
      List<Producto> lista = productoDao.listarProducto();
   
      DefaultTableModel tableModel = new DefaultTableModel(null,col);
      
     
      
      lista.forEach(pr->{
       
        tableModel.addRow(new Object[]{
          pr.getId(),
            pr.getCodigo(),
            pr.getDescripcion(),
            pr.getMarca(),
            pr.getModelo(),
            pr.getCantidad(),
            "$"+pr.getValor()
        
        });
      
      });
      
      
      
      
      
      
      tblproductos.setModel(tableModel);
      
        this.AjusteTabla();
   
  }

    private void limpiarCampos() {
        this.txtcodigo.setText("");
        this.txtmarca.setText("");
        this.txtnombre.setText("");
        this.txtmodelo.setText("");
        this.spcantidad.setValue(Integer.valueOf(0));
        this.spvalor.setValue(Integer.valueOf(0));
    }
    
    private void AjusteTabla(){
    
      tblproductos.getColumnModel().getColumn(0).setMinWidth(50);
      tblproductos.getColumnModel().getColumn(0).setPreferredWidth(50);
      tblproductos.getColumnModel().getColumn(0).setMaxWidth(50);
      
      tblproductos.getColumnModel().getColumn(1).setMinWidth(80);
      tblproductos.getColumnModel().getColumn(1).setPreferredWidth(80);
      tblproductos.getColumnModel().getColumn(1).setMaxWidth(80);
      
      tblproductos.getColumnModel().getColumn(2).setMinWidth(450);
      tblproductos.getColumnModel().getColumn(2).setPreferredWidth(450);
      tblproductos.getColumnModel().getColumn(2).setMaxWidth(450);
    }
}
